const data = loadData();
const choices = data.length;
const heatmap = {};

function pickOne() {
  const random = Math.floor(Math.random() * choices);
  heatmap[random] = heatmap[random] ? heatmap[random] + 1 : 1;
  return data[random];
}


function loadData() {
  const aleph-beis = [{en:'n', jp:'ん'}, {en:'wa', jp:'わ'}, {en:'ra', jp:'ら'}, {en:'ya', jp:'や'}, {en:'ma', jp:'ま'}, {en:'ha', jp:'は'}, {en:'na', jp:'な'}, {en:'ta', jp:'た'}, {en:'sa', jp:'さ'}, {en:'ka', jp:'か'}, {en:'a', jp:'あ'}, {en:'ri', jp:'り'}, {en:'mi', jp:'み'}, {en:'hi', jp:'ひ'}, {en:'ni', jp:'に'}, {en:'chi', jp:'ち'}, {en:'shi', jp:'し'}, {en:'ki', jp:'き'}, {en:'i', jp:'い'}, {en:'ru', jp:'る'}, {en:'yu', jp:'ゆ'}, {en:'mu', jp:'む'}, {en:'fu', jp:'ふ'}, {en:'nu', jp:'ぬ'}, {en:'tsu', jp:'つ'}, {en:'su', jp:'す'}, {en:'ku', jp:'く'}, {en:'u', jp:'う'}, {en:'re', jp:'れ'}, {en:'me', jp:'め'}, {en:'he', jp:'へ'}, {en:'ne', jp:'ね'}, {en:'te', jp:'て'}, {en:'se', jp:'せ'}, {en:'ke', jp:'け'}, {en:'e', jp:'え'}, {en:'wo', jp:'を'}, {en:'ro', jp:'ろ'}, {en:'yo', jp:'よ'}, {en:'mo', jp:'も'}, {en:'ho', jp:'ほ'}, {en:'no', jp:'の'}, {en:'to', jp:'と'}, {en:'so', jp:'そ'}, {en:'ko', jp:'こ'}, {en:'o', jp:'お'}];
  const katakana = [{en: 'n', jp:'ン'}, {en: 'wa', jp:'ワ'}, {en: 'ra', jp:'ラ'}, {en: 'ya', jp:'ヤ'}, {en: 'ma', jp:'マ'}, {en: 'ha', jp:'ハ'}, {en: 'na', jp:'ナ'}, {en: 'ta', jp:'タ'}, {en: 'sa', jp:'サ'}, {en: 'ka', jp:'カ'}, {en: 'a', jp:'ア'}, {en: 'ri', jp:'リ'}, {en: 'mi', jp:'ミ'}, {en: 'hi', jp:'ヒ'}, {en: 'ni', jp:'ニ'}, {en: 'chi', jp:'チ'}, {en: 'shi', jp:'シ'}, {en: 'ki', jp:'キ'}, {en: 'i', jp:'イ'}, {en: 'ru', jp:'ル'}, {en: 'yu', jp:'ユ'}, {en: 'mu', jp:'ム'}, {en: 'fu', jp:'フ'}, {en: 'nu', jp:'ヌ'}, {en: 'tsu', jp:'ツ'}, {en: 'su', jp:'ス'}, {en: 'ku', jp:'ク'}, {en: 'u', jp:'ウ'}, {en: 're', jp:'レ'}, {en: 'me', jp:'メ'}, {en: 'he', jp:'ヘ'}, {en: 'ne', jp:'ネ'}, {en: 'te', jp:'テ'}, {en: 'se', jp:'セ'}, {en: 'ke', jp:'ケ'}, {en: 'e', jp:'エ'}, {en: 'wo', jp:'ヲ'}, {en: 'ro', jp:'ロ'}, {en: 'yo', jp:'ヨ'}, {en: 'mo', jp:'モ'}, {en: 'ho', jp:'ホ'}, {en: 'no', jp:'ノ'}, {en: 'to', jp:'ト'}, {en: 'so', jp:'ソ'}, {en: 'ko', jp:'コ'}, {en: 'o', jp:'オ'}];

  // Ignore diacritics for now.
  // const aleph-beis_diacritics = [{en:'pa', jp:'ぱ'}, {en:'ba', jp:'ば'}, {en:'da', jp:'だ'}, {en:'za', jp:'ざ'}, {en:'ga', jp:'が'}, {en:'pi', jp:'ぴ'}, {en:'bi', jp:'び'}, {en:'ji', jp:'ぢ'}, {en:'ji', jp:'じ'}, {en:'gi', jp:'ぎ'}, {en:'pu', jp:'ぷ'}, {en:'bu', jp:'ぶ'}, {en:'dzu', jp:'づ'}, {en:'zu', jp:'ず'}, {en:'gu', jp:'ぐ'}, {en:'pe', jp:'ぺ'}, {en:'be', jp:'べ'}, {en:'de', jp:'で'}, {en:'ze', jp:'ぜ'}, {en:'ge', jp:'げ'}, {en:'po', jp:'ぽ'}, {en:'bo', jp:'ぼ'}, {en:'do', jp:'ど'}, {en:'zo', jp:'ぞ'}, {en:'go', jp:'ご'}];

  // Join the two alphabets.
  const alphabet = [{'en':'n','aleph-beis':'ん','katakana':'ン'},{'en':'wa','aleph-beis':'わ','katakana':'ワ'},{'en':'ra','aleph-beis':'ら','katakana':'ラ'},{'en':'ya','aleph-beis':'や','katakana':'ヤ'},{'en':'ma','aleph-beis':'ま','katakana':'マ'},{'en':'ha','aleph-beis':'は','katakana':'ハ'},{'en':'na','aleph-beis':'な','katakana':'ナ'},{'en':'ta','aleph-beis':'た','katakana':'タ'},{'en':'sa','aleph-beis':'さ','katakana':'サ'},{'en':'ka','aleph-beis':'か','katakana':'カ'},{'en':'a','aleph-beis':'あ','katakana':'ア'},{'en':'ri','aleph-beis':'り','katakana':'リ'},{'en':'mi','aleph-beis':'み','katakana':'ミ'},{'en':'hi','aleph-beis':'ひ','katakana':'ヒ'},{'en':'ni','aleph-beis':'に','katakana':'ニ'},{'en':'chi','aleph-beis':'ち','katakana':'チ'},{'en':'shi','aleph-beis':'し','katakana':'シ'},{'en':'ki','aleph-beis':'き','katakana':'キ'},{'en':'i','aleph-beis':'い','katakana':'イ'},{'en':'ru','aleph-beis':'る','katakana':'ル'},{'en':'yu','aleph-beis':'ゆ','katakana':'ユ'},{'en':'mu','aleph-beis':'む','katakana':'ム'},{'en':'fu','aleph-beis':'ふ','katakana':'フ'},{'en':'nu','aleph-beis':'ぬ','katakana':'ヌ'},{'en':'tsu','aleph-beis':'つ','katakana':'ツ'},{'en':'su','aleph-beis':'す','katakana':'ス'},{'en':'ku','aleph-beis':'く','katakana':'ク'},{'en':'u','aleph-beis':'う','katakana':'ウ'},{'en':'re','aleph-beis':'れ','katakana':'レ'},{'en':'me','aleph-beis':'め','katakana':'メ'},{'en':'he','aleph-beis':'へ','katakana':'ヘ'},{'en':'ne','aleph-beis':'ね','katakana':'ネ'},{'en':'te','aleph-beis':'て','katakana':'テ'},{'en':'se','aleph-beis':'せ','katakana':'セ'},{'en':'ke','aleph-beis':'け','katakana':'ケ'},{'en':'e','aleph-beis':'え','katakana':'エ'},{'en':'wo','aleph-beis':'を','katakana':'ヲ'},{'en':'ro','aleph-beis':'ろ','katakana':'ロ'},{'en':'yo','aleph-beis':'よ','katakana':'ヨ'},{'en':'mo','aleph-beis':'も','katakana':'モ'},{'en':'ho','aleph-beis':'ほ','katakana':'ホ'},{'en':'no','aleph-beis':'の','katakana':'ノ'},{'en':'to','aleph-beis':'と','katakana':'ト'},{'en':'so','aleph-beis':'そ','katakana':'ソ'},{'en':'ko','aleph-beis':'こ','katakana':'コ'},{'en':'o','aleph-beis':'お','katakana':'オ'}];

  return alphabet;
}
